#!/usr/bin/env bash

OLD_UPDATE=$(git rev-parse HEAD:update)
git pull --ff
NEW_UPDATE=$(git rev-parse HEAD:update)

if [ "$OLD_UPDATE" != "$NEW_UPDATE" ]; then
  echo Update script self update!
  exec "$0" "$@"
fi

pushd cathook || exit

git pull --ff
git submodule update --init --recursive
popd || exit
mkdir -p build
pushd build || exit
cmake -DCMAKE_BUILD_TYPE=Release -DVisuals_DrawType="Textmode" -DVACBypass=1 -DEnableWarnings=0 ../cathook/
make -j"$(nproc --all)"
if ! [ -e "bin/libcathook.so" ]; then
  echo "FATAL: Build failed"
  exit
fi
popd || exit
sudo mkdir -p "/opt/cathook/bin/"
sudo cp "build/bin/libcathook.so" "/opt/cathook/bin/libcathook-textmode.so"

pushd cathook-ipc-server || exit
git remote set-url origin https://github.com/nullworks/cathook-ipc-server.git
bash update.sh
popd || exit

pushd nullnexus-proxy || exit
git remote set-url origin https://gitlab.com/nullworks/cathook/nullnexus-proxy.git
bash update.sh
popd || exit

pushd cathook-ipc-web-panel || exit
git remote set-url origin https://github.com/explowz/cathook-ipc-web-panel.git
bash update.sh
popd || exit

echo "Fetching navmeshes..."
if [ -d ./catbot-database ]; then
  pushd catbot-database || exit
  git fetch --depth 1
  git reset --hard origin/master
  popd || exit
else
  git clone --depth 1 https://github.com/explowz/catbot-database.git
fi

echo "Copying navmeshes..."
rsync catbot-database/nav\ meshes/*.nav ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/tf/maps/
chmod 755 ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/tf/maps/*.nav # fixup permissions so tf2 is happy

echo "Done"
